[Feature] Add Declarative Package Management
* Add component/os specific yaml package manifests to packages dir and
  symlink contents to .chezmoidata (so the contents are available in
  templates)
* Add component/os specific yaml package management scripts that make
  use of aforementioned manifests
* Add helper templates for use in aforementioned scripts
* Add iterm2 config as a symlink to avoid messy diffs
* Update s searxng custom provider to use https (instead of http)
* Add install.sh script, as well as os specific bootstrapping scripts,
  that enable fresh installation on a new machine
* Remove components to DARWIN.md that are now managed by chezmoi
* Update completion script to load brew completions
* Update bashrc PATH definition to prepend known paths to existing path,
  instead of appending them
* Add git-credentials to dotfiles
* Remove unused git alias from gitconfig

diff --git a/dot_bash_completion.tmpl b/dot_bash_completion.tmpl
--- a/dot_bash_completion.tmpl
+++ b/dot_bash_completion.tmpl
@@ -1,19 +1,66 @@
-{{ if eq .chezmoi.os "darwin" -}}
+{{- if eq .chezmoi.os "darwin" -}}
 #!/usr/bin/env bash
 
 
+# TODO: replace echos w/ logger calls
+
+## custom ######################################################################
+
 if [[ -z "${COMPLETION_DIR+x}" ]]; then
-    echo "[ERROR] completions dir env var is unset"
+    # echo "[ERROR] completion dir env var is unset"
     return 1
 fi
 
 if [[ ! -d "${COMPLETION_DIR}" ]]; then
-    echo "[INFO] creating completions dir='${COMPLETION_DIR}'"
+    # echo "[INFO] creating completion dir='${COMPLETION_DIR}'"
     mkdir "${COMPLETION_DIR}"
 fi
 
-for file in $(ls "${COMPLETION_DIR}"); do
-    source "${COMPLETION_DIR}/${file}"
+# echo "[INFO] loading contents of completion dir='${COMPLETION_DIR}'"
+
+for FILE in "${COMPLETION_DIR}"/*; do
+    source "${FILE}"
 done
 
+## homebrew ####################################################################
+
+if ! which brew > /dev/null; then
+    # echo "[ERROR] brew is not installed"
+    retrun 1
+fi
+
+if [[ -z "${SYS_CONFIG+x}" ]]; then
+    # echo "[ERROR] SYS_CONFIG dir is not set"
+    return 1
+fi
+
+if [[ ! -d "${SYS_CONFIG}" ]]; then
+    # echo "[ERROR] SYS_CONFIG dir does not exist"
+    return 1
+fi
+
+BREW_COMPLETION_ROOT="${SYS_CONFIG}/profile.d"
+BREW_COMPLETION_SCRIPT="${BREW_COMPLETION_ROOT}/bash_completion.sh"
+BREW_COMPLETION_DIR="${BREW_COMPLETION_ROOT}/bash_completion.d"
+
+if [[ -f "${BREW_COMPLETION_SCRIPT}" ]] && [[ ! -d "${BREW_COMPLETION_DIR}/" ]]; then
+    # echo "[WARN] homebrew completion script='${BREW_COMPLETION_SCRIPT}' does not exist"
+    # echo "[WARN] homebrew completion dir=${BREW_COMPLETION_DIR} does not exist"
+    return 0
+fi
+
+if [[ -f "${BREW_COMPLETION_SCRIPT}" ]]; then
+    # echo "[INFO] loading homebrew completion script='${BREW_COMPLETION_SCRIPT}'"
+    source "${BREW_COMPLETION_SCRIPT}"
+fi
+
+if [[ ! -d "${BREW_COMPLETION_DIR}/" ]]; then
+    return 0
+fi
+
+# echo "[INFO] loading contents of homebrew completion dir='${BREW_COMPLETION_DIR}'"
+
+for FILE in "${BREW_COMPLETION_DIR}/"*; do
+  source "${FILE}"
+done
 {{ end }}
