[Enhance] Miscellaneous Tmux Enhancements and Fixes
* Add helper functions for reading/writing tmux env and tmux layout env
  values

diff --git a/chezmoi/dot_config/tmux/scripts/executable_resize-layout b/chezmoi/dot_config/tmux/scripts/executable_resize-layout
--- a/chezmoi/dot_config/tmux/scripts/executable_resize-layout
+++ b/chezmoi/dot_config/tmux/scripts/executable_resize-layout
@@ -2,8 +2,10 @@
 
 set -Eeuo pipefail
 
+source "${CODE_ROOT}/lib/bash/utils.sh"
 
-USAGE="resize-layout [-l layout] [-t window] [-s path]"
+
+USAGE="resize-layout [-l layout] [-t window] [-s path] [--strict] [--force]"
 
 usage() {
     echo "usage: ${USAGE}"
@@ -50,10 +52,10 @@ OPTIONS
     -l, --layout        optional; if not provided, will pull value from window name if in the format  ".* \(layout-type\)"; the layout to use
     -t, --target        optional, defaults to the active window; the name of the window for which to set a layout
     -s, --specs         optional, default to "${HOME}/.config/tmux/layouts"; a file that contains layout specifications in the format describe about
-    -v, --verbose       optional; write progress/status messages to stdout
     --strict            optional; can't be used w/ --dry-run; if specified, error cases will case the script to exit with non-zero return codes; see above for specific
                         behavioral description
     --force             optional; if specified, forces resize even if pane dimensions match those in the layout spec
+    -v, --verbose       optional; write progress/status messages to stdout
     --dry-run           optional; can't be used w/ --force; indicates that the script should print hypothetical results to the console, but make no state changes
     -h, --help          display this message
 help
@@ -81,6 +83,20 @@ log_and_exit() {
 
     [[ -n "$VERBOSE" ]] && echo "[WARN] ${1}" || echo -n ""
     exit 0
+}
+
+__extract_layout_from_name() {
+    # FIXME: the pattern used to extract the layout-type from window name should not allow whitespace
+    #        characters, and should probably be restricted to alphanumeric and hyphens + underscores;
+    #        I couldn't for the life of me get that pattern to work
+    [[ "${TARGET}" =~ .*[[:space:]]\((.*)\)$ ]] && echo "${BASH_REMATCH[1]}" || echo ""
+}
+
+__extract_layout_from_env() {
+    local env_var="TMUX_$(to_upper "${TARGET}_LAYOUT")"
+    local env_val="$(tmux show-environment "${env_var}" 2> /dev/null || echo "")"
+
+    echo "${env_val}" | cut -d "=" -f2
 }
 
 
@@ -122,7 +138,6 @@ while [[ $# -gt 0 ]]; do
       exit 0
       ;;
     *)
-      echo "${1}"
       usage
       exit 1
       ;;
@@ -157,15 +172,16 @@ fi
 log "preparing to set layout for target window='${TARGET}' (id: ${TARGET_ID})"
 
 # if layout-type isn't provided, try to extract it from window name
-if [[ -z "${LAYOUT}" ]]; then
-    # FIXME: the pattern used to extract the layout-type from window name should not allow whitespace
-    #        characters, and should probably be restricted to alphanumeric and hyphens + underscores;
-    #        I couldn't for the life of me get that pattern to work
-    LAYOUT="$([[ "${TARGET}" =~ .*[[:space:]]\((.*)\)$ ]] && echo "${BASH_REMATCH[1]}" || echo "")"
+[[ -z "${LAYOUT}" ]] && LAYOUT="$(__extract_layout_from_name)"
 
-    EXTRACTED_LAYOUT_MSG="$([[ -z "${LAYOUT}" ]] && echo "no layout extracted" || echo "extracted layout='${LAYOUT}'")"
-    log "no layout provided; ${EXTRACTED_LAYOUT_MSG} from window name='${TARGET}'"
+if [[ -n "${LAYOUT}" ]]; then
+    log "no layout provided; extracted layout='${LAYOUT}' from window name='${TARGET}'"
+else
+    LAYOUT="$(__extract_layout_from_env)"
+    [[ -n "${LAYOUT}" ]] && log "no layout provided; extracted layout='${LAYOUT}' from tmux env"
 fi
+
+[[ -z "${LAYOUT}" ]] && log "no layout provided; unable to extract layout"
 
 if [[ ! -f "${SPEC_PATH}" ]]; then
     log_and_exit "spec file='${SPEC_PATH}' does not exist"
@@ -186,7 +202,7 @@ if [[ -z "${SPEC_MATCH}" ]]; then
     log_and_exit "no layout specification found for '${IDENTIFIER}'"
 fi
 
-log "found spec match='${SPEC_MATCH}'"
+log "found spec match(es)='${SPEC_MATCH}'"
 
 # ensure that we have only one match for the current identifier; if the original match is
 # different from this "single match", we know we originally found > 1 match
