[Feature] Add ble.sh
* Add call to ble.sh installation script in darwin and linux manifests
* Add ble.sh initialization in bashrc
* Add initial blerc
* Update darwin package installation hook script to run generic
  installation scripts
* Update linux package installation hook script to use pkgmgr to run
  install scripts

diff --git a/scripts/hooks/run_after_D_install-packages--darwin.sh.tmpl b/scripts/hooks/run_after_D_install-packages--darwin.sh.tmpl
--- a/scripts/hooks/run_after_D_install-packages--darwin.sh.tmpl
+++ b/scripts/hooks/run_after_D_install-packages--darwin.sh.tmpl
@@ -26,16 +26,25 @@ echo "[INFO] installing brew casks"
 brew list {{ $cask }} --cask &> /dev/null || brew install {{ $cask }} --cask
 {{- end }}
 
+echo "[INFO] installing from scripts"
+
+{{- range $script := .packages.darwin.scripts }}
+# assume the script is os specific
+SCRIPT_PATH="${SCRIPTS_ROOT}/install/{{ $.chezmoi.os }}/{{ $script.name }}.sh"
+# but if the os specific path doesn't exist, it may be an os-agnostic script
+[[ ! -f "${SCRIPT_PATH}" ]] && SCRIPT_PATH="${SCRIPTS_ROOT}/install/generic/{{ $script.name }}.sh"
+# if that doesn't exist, fail
+[[ ! -f "${SCRIPT_PATH}" ]] && echo "[ERROR] the script ${SCRIPT_PATH} doesn't exist" && exit 1
+"${SCRIPT_PATH}" {{ dig "args" list $script | join " " }}
+{{- end }}
+
+# NOTE: at the time of writing, go packages must be installed after scripts due to
+# dependency on gvm
+
 echo "[INFO] installing go packages"
 
 {{- range $pkg := .packages.darwin.go }}
 which "{{ $pkg.name }}" > /dev/null || go install "{{ $pkg.url }}@{{ $pkg.version }}"
-{{- end }}
-
-echo "[INFO] installing from scripts"
-
-{{- range $script := .packages.darwin.scripts }}
-{{ print (env "SCRIPTS_ROOT") "/install/" $.chezmoi.os "/" $script.name ".sh" }} {{ $script.args | join " " }}
 {{- end }}
 
 {{- end }}
